import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import Link from "next/link"
import { ThemeProvider } from "@/providers/theme-provider"

import { ThemeSwitcher } from "@/components/theme-switcher"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="bg-background sticky top-0 z-50 border-b">
            <div className="container flex h-14 items-center justify-between">
              <Link href="/" className="text-xl font-semibold">
                Next Template
              </Link>
              <ThemeSwitcher />
            </div>
          </header>
          <main className="flex grow flex-col">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
